{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenforce.secretName" . }}
  labels:
    {{- include "greenforce.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  S3_ENDPOINT_URL: {{ .Values.secrets.s3EndpointUrl | quote }}
  S3_REGION: {{ .Values.secrets.s3Region | quote }}
{{- end }}
