---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeo-workspace
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity | quote }}   
---