{{- if not .Values.persistence.existingVolume.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeo-workspace
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.capacity | quote }}   
---
{{- end }}