{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openeo-argo.serviceAccountName" . }}
  labels:
    {{- include "openeo-argo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openeo-argo-pods-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openeo-argo-pods-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openeo-argo-pods-role
subjects:
- kind: ServiceAccount
  name: {{ include "openeo-argo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
