{{- if eq .Values.ingestion.mode "push" }}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "rolling-archive.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rolling-archive.labels" . | nindent 4 }}
spec:
  eventBusName: {{ include "rolling-archive.fullname" . }}

  template:
    serviceAccountName: {{ include "rolling-archive.serviceAccountName" . }}

  dependencies:
    - name: cdse-event-priority
      eventSourceName: {{ include "rolling-archive.fullname" . }}
      eventName: priority
    - name: cdse-event-other
      eventSourceName: {{ include "rolling-archive.fullname" . }}
      eventName: other

  triggers:
    - template:
        name: kafka-trigger-priority
        conditions: cdse-event-priority
        kafka:
          url: {{ .Values.kafka.bootstrap | quote }}
          topic: {{ .Values.kafka.topics.downloadHigh | quote }}
          payload:
            - src:
                dependencyName: cdse-event-priority
                dataKey: body
                useRawData: true
              dest: "."

    - template:
        name: kafka-trigger-other
        conditions: cdse-event-other
        kafka:
          url: {{ .Values.kafka.bootstrap | quote }}
          topic: {{ .Values.kafka.topics.downloadNormal | quote }}
          payload:
            - src:
                dependencyName: cdse-event-other
                dataKey: body
                useRawData: true
              dest: "."
{{- end }}
