{{- if eq .Values.ingestion.mode "push" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rolling-archive.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rolling-archive.labels" . | nindent 4 }}
{{- end }}
