dask-gateway:
  gateway:
    image:
      name: ghcr.io/eodcgmbh/container-images/dask-gateway-server-jwt
      tag: 2025.8.0
      pullPolicy: Always
    backend:
      image:
        pullPolicy: Always

  controller:
    image:
      name: ghcr.io/eodcgmbh/container-images/dask-gateway-server-jwt
      tag: 2025.8.0
      pullPolicy: Always
