apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository:  oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: EODAG (Earth Observation Data Access Gateway) is a tool for searching,
  aggregating results and downloading remote sensed images offering a unified API
  for data access regardless of the data provider. This chart deploys EODC's custom
  EODAG server implementation with DEIMS OARec plugin support.
home: https://git.eodc.eu/eodc/eodag-server
icon: https://raw.githubusercontent.com/CS-SI/eodag/master/docs/_static/eodag_bycs.png
name: eodag-server
sources:
- https://git.eodc.eu/eodc/eodag-server
type: application
version: 0.1.0
