apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jeg-rolebinding
  namespace: {{ .Release.Namespace }} 
subjects:
  - kind: ServiceAccount
    name: enterprise-gateway-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kip-controller