# name: Release JupyterHub Charts

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     tags:
#       - "jupyterhub-*"
#     paths:
#       - eodc/jupyterhub/**

# jobs:
#   release:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v5
#         with:
#           fetch-depth: 0

#       - name: Configure Git
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
#       - name: Install Helm
#         uses: azure/setup-helm@v4
      
#       - name: add repos
#         run: |
#           helm repo add jupyterhub https://hub.jupyter.org/helm-chart/
#           helm repo add binderhub-service https://2i2c.org/binderhub-service
      
#       - name: Install Homebrew
#         uses: Homebrew/actions/setup-homebrew@main
      
#       - name: Install Chart Releaser via Homebrew
#         run: |
#           brew tap helm/tap
#           brew install chart-releaser

#       - name: Release JupyterHub chart
#         env:
#           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#         run: |
#           cr package eodc/jupyterhub
#           cr upload --owner eodcgmbh --token $CR_TOKEN --git-repo charts --packages-with-index --push --skip-existing 
#           cr index --owner eodcgmbh --token $CR_TOKEN --git-repo charts --packages-with-index --index-path . --push

#       # - name: Run chart-releaser
#       #   uses: helm/chart-releaser-action@v1.7.0
#       #   with:
#       #     charts_dir: eodc/jupyterhub
#       #     packages_with_index: True
#       #   env:
#       #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"