apiVersion: v1
kind: Service
metadata:
  name: {{ include "pygeoapi.fullname" . }}
  labels:
    {{- include "pygeoapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pygeoapi.service.type }}
  ports:
    - port: {{ .Values.pygeoapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pygeoapi.selectorLabels" . | nindent 4 }}
