{{- if .Values.pygeoapi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pygeoapi.serviceAccountName" . }}
  labels:
    {{- include "pygeoapi.labels" . | nindent 4 }}
  {{- with .Values.pygeoapi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
